name: api_client
resolution: workspace
version: 0.1.0
environment:
  sdk: ^3.10.0
publish_to: none

dependencies:
  domain:
    path: ../domain
  graphql_flutter: ^5.2.0-beta.7
  meta: ^1.11.0

dev_dependencies:
  build: ^2.5.4
  build_runner: ^2.4.9
  graphql_codegen: ^1.2.2
  lints: ^5.0.0
