name: windows_widget
resolution: workspace
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  domain:
    path: ../packages/domain
  api_client:
    path: ../packages/api_client
  graphql_flutter: ^5.2.0-beta.7
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
